spring:
  application:
    name: cassandra-cdc

  cassandra:
    contact-points: 172.23.152.11:9042
    keyspace-name: cdc_testing
    schema-action: create_if_not_exists
    local-datacenter: datacenter1

cassandra:
  cdc:
    log-path: /home/baodh/cdc-lab/cassandra-data/cdc_raw
    table-includes:
      - alarm

# Messaging
messaging:
  client:
    ## Producer
    producer:
      bootstrap-servers: 10.20.3.62:9092
      acks: all
      linger-ms: 5
      retries: 3
      retry-backoff-ms: 100
      enable-idempotence: true

  ## Produce
  producers:
    internal:
      alarm-data:
        topic: alarmManager.response.alarmWebsocket
