spring:
  application:
    name: cassandra-cdc

  cassandra:
    contact-points: ndl-cassandra.ndl:9042
    keyspace-name: alarm
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra

cassandra:
  cdc:
    log-path: /cassandra-data/data/cdc_raw
    table-includes:
      - alarm

# Messaging
messaging:
  client:
    ## Producer
    producer:
      bootstrap-servers: ndl-cp-kafka.ndl:9092
      acks: all
      linger-ms: 5
      retries: 3
      retry-backoff-ms: 100
      enable-idempotence: true

  ## Produce
  producers:
    internal:
      alarm-data:
        topic: alarmManager.response.alarmWebsocket
