cluster_name: 'Cassandra Cluster'

num_tokens: 16

allocate_tokens_for_local_replication_factor: 3

hinted_handoff_enabled: true

max_hint_window: 3h

hinted_handoff_throttle: 1024KiB

max_hints_delivery_threads: 2

hints_directory: /var/lib/cassandra/data/hints

hints_flush_period: 10000ms

max_hints_file_size: 128MiB

auto_hints_cleanup_enabled: false

batchlog_replay_throttle: 1024KiB

authenticator: AllowAllAuthenticator

authorizer: AllowAllAuthorizer

role_manager: CassandraRoleManager

network_authorizer: AllowAllNetworkAuthorizer

cidr_authorizer:
  class_name: AllowAllCIDRAuthorizer

roles_validity: 2000ms
permissions_validity: 2000ms
credentials_validity: 2000ms

partitioner: org.apache.cassandra.dht.Murmur3Partitioner

data_file_directories:
  - /var/lib/cassandra/data/data

commitlog_directory: /var/lib/cassandra/data/commitlog

cdc_enabled: true
cdc_block_writes: false
cdc_raw_directory: /var/lib/cassandra/data/cdc_raw
disk_failure_policy: stop
commit_failure_policy: stop

prepared_statements_cache_size:

key_cache_size:
key_cache_save_period: 4h

row_cache_size: 0MiB
row_cache_save_period: 0s

counter_cache_size:
counter_cache_save_period: 7200s
saved_caches_directory: /var/lib/cassandra/data/saved_caches

commitlog_sync: periodic
commitlog_sync_period: 10000ms
commitlog_segment_size: 32MiB
commitlog_disk_access_mode: legacy

seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      - seeds: "127.0.0.1:7000"

concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32
concurrent_materialized_view_writes: 32

memtable:
  configurations:
    skiplist:
      class_name: SkipListMemtable
    trie:
      class_name: TrieMemtable
    default:
      inherits: skiplist
memtable_allocation_type: heap_buffers

cdc_total_space: 4096MiB
cdc_free_space_check_interval: 250ms

index_summary_capacity:
index_summary_resize_interval: 60m

trickle_fsync: false
trickle_fsync_interval: 10240KiB

storage_port: 7000

ssl_storage_port: 7001

listen_address: localhost

start_native_transport: true

native_transport_port: 9042

native_transport_allow_older_protocols: true

rpc_address: localhost

rpc_keepalive: true

incremental_backups: false

snapshot_before_compaction: false
auto_snapshot: true
snapshot_links_per_second: 0

column_index_cache_size: 2KiB

concurrent_materialized_view_builders: 1

compaction_throughput: 64MiB/s

sstable_preemptive_open_interval: 50MiB
uuid_sstable_identifiers_enabled: false

read_request_timeout: 5000ms

range_request_timeout: 10000ms

write_request_timeout: 2000ms

counter_write_request_timeout: 5000ms

cas_contention_timeout: 1000ms

truncate_request_timeout: 60000ms

request_timeout: 10000ms

slow_query_log_timeout: 500ms

endpoint_snitch: SimpleSnitch

dynamic_snitch_update_interval: 100ms
dynamic_snitch_reset_interval: 600000ms
dynamic_snitch_badness_threshold: 1.0

crypto_provider:
  - class_name: org.apache.cassandra.security.DefaultCryptoProvider
    parameters:
      - fail_on_missing_provider: "false"

server_encryption_options:
  internode_encryption: none
  legacy_ssl_storage_port_enabled: false
  keystore: conf/.keystore
  require_client_auth: false
  truststore: conf/.truststore
  require_endpoint_verification: false

client_encryption_options:
  enabled: false
  keystore: conf/.keystore
  require_client_auth: false

internode_compression: dc

inter_dc_tcp_nodelay: false

trace_type_query_ttl: 1d
trace_type_repair_ttl: 7d

user_defined_functions_enabled: false

transparent_data_encryption_options:
  enabled: false
  chunk_length_kb: 64
  cipher: AES/CBC/PKCS5Padding
  key_alias: testing:1
  
  key_provider:
    - class_name: org.apache.cassandra.security.JKSKeyProvider
      parameters:
        - keystore: conf/.keystore
          keystore_password: cassandra
          store_type: JCEKS
          key_password: cassandra

tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000

replica_filtering_protection:
  cached_rows_warn_threshold: 2000
  cached_rows_fail_threshold: 32000

batch_size_warn_threshold: 5KiB

batch_size_fail_threshold: 50KiB

unlogged_batch_across_partitions_warn_threshold: 10

audit_logging_options:
  enabled: false
  logger:
    - class_name: BinAuditLogger

diagnostic_events_enabled: false

repaired_data_tracking_for_range_reads_enabled: false
repaired_data_tracking_for_partition_reads_enabled: false

report_unconfirmed_repaired_data_mismatches: false

materialized_views_enabled: false

sasi_indexes_enabled: false

transient_replication_enabled: false

drop_compact_storage_enabled: false

storage_compatibility_mode: CASSANDRA_4